<?php

namespace App\Services\Common\Helpers;

class Merchant
{
    const HAS_FAILED_TRANSACTIONS = 'HAS_FAILED_TRANSACTIONS';
    const HAS_FAILED_WITHDRAW = 'HAS_FAILED_WITHDRAW';
    const HAS_FAILED_CREATE_WITHDRAW = 'HAS_FAILED_CREATE_WITHDRAW';
    const HAS_WAIT_FOR_COMPLETE_WITHDRAW = 'HAS_WAIT_FOR_COMPLETE_WITHDRAW';
    const HAS_SUCCESS_WITHDRAW = 'HAS_SUCCESS_WITHDRAW';
    const NOT_NEED_TO_WITHDRAW = 'NOT_NEED_TO_WITHDRAW';
}