<?php
/**
 * Created by PhpStorm.
 * User: Ladmin
 * Date: 02.09.2019
 * Time: 17:13
 */

return [
    "types" =>[
        0 => 'SearchCard',
        1 => 'GetCardList',
        2 => 'GetBalance',
        3 => 'BlockCard',
        4 => 'UnblockCard',
        5 => 'SendTransactionToAbs',
        6 => 'RucardBlockAmount',
        7 => 'RucardConfirm',
        8 => 'RucardCancel',
        9 => 'RucardFill',
        10 => 'RucardCardToCard',
        11 => 'SendToPaymentSystem',
        12 => 'AbsAccountToAccount',
        13 => 'AbsBLockAmountAndConfirm',
        14 => 'AbsFill',
        15 => 'CallbackGetUserAccounts',
        16 => 'AccountTransactions',
        17 => 'GetBalances',
        18 => 'CardTransactions',
        19 => 'CreditTransactions',
        20 => 'DepositTransactions',
        21 => 'GetAccountList',
        22 => 'GetDepositList',
        23 => 'GetTransfer',
        24 => 'GetCreditList',
        25 => 'GetCreditFact',
        26 => 'GetCreditPlan',
        27 => 'AbsLiquidation',
        28 => 'AbsCurrencyExchangeBlock',
        29 => 'AbsCurrencyExchangeFill',
        30 => 'AbsCurrencyExchangeLiquidation',
        31 => 'SoniyaSend',
        32 => 'SoniyaConfirm',
        33 => 'CreateInsuranceDeposit',
        34 => 'CreateCardContract',
        35 => 'CallMeBack',
        36 => 'IssuingMerchantMoney',
        37 => 'ForeignCardAttach',
        38 => 'GetStateForeignCardAttach',
        39 => 'GetClientInfo',
        40 => 'FillFromForeign',
        41 => 'TKBPaymentWithFrame',
        42 => 'TKBGetPaymentState',
        43 => 'IdentificationSearchClient',
        44 => 'IdentificationCreateClient',
        45 => 'RegisterClientInAbs',
        46 => 'IdentificationUpdateClient',
        47 => 'SoniyaCreateAndConfirm',
        48 => 'SoniyaCheckStatusPayment',
        49 => 'QrCheckStatusPaymentDefferedCallback',
        50 => 'BPCVisaBlockAmount',
        51 => 'BPCVisaBlockCard',
        52 => 'BPCVisaUnblockCard',
        53 => 'BPCVisaCancel',
        54 => 'BPCVisaFill',
        55 => 'BPCVisaCardToCard',
        56 => 'BPCVisaGetBalance',
        57 => 'MTMBlockAmount',
        58 => 'MTMBlockCard',
        59 => 'MTMUnblockCard',
        60 => 'MTMCancel',
        61 => 'MTMFill',
        62 => 'MTMCardToCard',
        63 => 'MTMGetBalance',
        64 => 'CreateDeposit',
        65 => 'CloseDeposit',
        66 => 'CreateAccount',
        67 => 'GetDepositContractCodec',
        68 => 'GetAccountContractCodec',
        69 => 'GetClientData',
    ]

];